# Generated by Django 4.1.4 on 2022-12-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationMind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('coop_mind_name', models.CharField(max_length=128, verbose_name='脑图名称')),
                ('creator_user_id', models.BigIntegerField(default=0, verbose_name='创建人ID')),
                ('client_uuid', models.CharField(max_length=64, verbose_name='客户端ID')),
                ('snapshot_data', models.TextField(null=True, verbose_name='脑图数据')),
                ('mind_log_id', models.BigIntegerField(null=True, verbose_name='data对应的操作日志(cooperation_mind_log)ID')),
                ('data_format', models.CharField(max_length=32, verbose_name='数据格式化类型')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否标记为软删除')),
            ],
            options={
                'verbose_name': '脑图表',
                'db_table': 'cooperation_mind',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CooperationMindStar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('operator_user_id', models.BigIntegerField(verbose_name='收藏人')),
                ('coop_mind_name', models.CharField(max_length=128, verbose_name='脑图名称')),
                ('coop_mind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.cooperationmind', verbose_name='脑图ID')),
            ],
            options={
                'verbose_name': '协作分享表',
                'db_table': 'cooperation_mind_star',
            },
        ),
        migrations.CreateModel(
            name='CooperationMindShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('coop_mind_name', models.CharField(max_length=128, verbose_name='脑图名称')),
                ('share_uuid', models.CharField(max_length=128, verbose_name='分享uuid')),
                ('share_uuid_hash', models.BigIntegerField(verbose_name='分享uuid_hash')),
                ('share_end_time', models.DateTimeField(null=True, verbose_name='分享有效期')),
                ('operator_user_id', models.BigIntegerField(verbose_name='分享操作人')),
                ('coop_mind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.cooperationmind', verbose_name='脑图ID')),
            ],
            options={
                'verbose_name': '协作分享表',
                'db_table': 'cooperation_mind_share',
            },
        ),
        migrations.CreateModel(
            name='CooperationMindLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('log_uuid', models.CharField(max_length=64, verbose_name='操作UUID')),
                ('log_content', models.CharField(max_length=1024, verbose_name='操作内容')),
                ('operator_user_id', models.BigIntegerField(null=True, verbose_name='操作人')),
                ('operator_ip', models.CharField(max_length=32, verbose_name='操作人IP')),
                ('client_uuid', models.CharField(max_length=64, verbose_name='客户端ID')),
                ('coop_mind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.cooperationmind', verbose_name='脑图ID')),
            ],
            options={
                'verbose_name': '操作日志表',
                'db_table': 'cooperation_mind_log',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cooperationmind',
            index=models.Index(fields=['creator_user_id'], name='cooperation_creator_b40e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperationmindstar',
            index=models.Index(fields=['operator_user_id'], name='cooperation_operato_fae2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperationmindshare',
            index=models.Index(fields=['share_uuid_hash'], name='cooperation_share_u_66be20_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperationmindshare',
            index=models.Index(fields=['operator_user_id'], name='cooperation_operato_f5cf97_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperationmindlog',
            index=models.Index(fields=['coop_mind_id'], name='cooperation_coop_mi_32e0df_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperationmindlog',
            index=models.Index(fields=['operator_user_id'], name='cooperation_operato_9d4daf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cooperationmindlog',
            unique_together={('coop_mind_id', 'log_uuid')},
        ),
    ]
